### PR TITLE
Add GPU PANDA

### PR DESCRIPTION
**Pull request by twangxxx**
- Add GPU PANDA

### CODE REVIEW

**Comment by marouenbg** [comment]
Hey @twangxxx , you need to update your local `devel` branch to get the latest changes, before opening the PR.
`git fetch upstream`
`git merge upstream/devel`
Then create PR. Thanks!

**Comment by twangxxx** [comment]
> Hey @twangxxx , you need to update your local `devel` branch to get the latest changes, before opening the PR.
> `git fetch upstream`
> `git merge upstream/devel`
> Then create PR. Thanks!

@marouenbg , I did! It looks good so far! excited!

**Comment by marouenbg** [comment]
@twangxxx look at the last commit, the left side does not correspond to the current `devel` branch. If you already created the new branch, then you probably need to rebase.

**Comment by twangxxx** [comment]
@marouenbg, for only the last commit, the left side doesn't match the current devel branch .travis.yml file, but when we see **changes from all commits** in this PR https://github.com/netZoo/netZooR/pull/138/files,  I think left side does match the current devel branch (e.g. no changes in .travis.yml file, which suggests this PR is based on the current devel branch).

What I did:
Given I have a branch named fix-issue#103, which is based on the previous devel branch (before deploying Jenkins) and I added some features in it.
Then, 
git fetch upstream,
git merge upstream/devel,
merge the devel into fix-issue#103 branch, then created this PR.

I don't think anything is wrong here(?), let me know your thoughts on this process.

**Comment by marouenbg** [comment]
ok makes sense, good job.

**Comment by marouenbg** [comment]
@twangxxx there is something weird about this PR. 
Here is your [current](https://github.com/netZoo/netZooR/blob/0cc51e5c7e15c7d549ca9c91ff181527c59838d6/.travis.yml ) `.travis.yml` , it is different from the one in `devel`, yet no changes are shown. I think the automatic mode of `merge` will keep the additions of both versions. You need a `rebase`.

**Comment by marouenbg** [comment]
or you could only take the `.travis.yml` from `devel` for now, but the `rebase` is the proper way of updating branches.

**Comment by twangxxx** [comment]
@marouenbg  Can you tell where is the difference? I didn't see any difference.

**Comment by marouenbg** [comment]
yes right there are no differences.

**Comment by twangxxx** [comment]
> yes right there are no differences.

@marouenbg , so let me remove all tests and run Jenkins build again.

**Comment by twangxxx** [comment]
@marouenbg this PR works well, I am gonna merge into devel then create a new PR to tackle unit tests.

**Pull request merged**
