### PR TITLE
add panda test network

### PR DESCRIPTION
**Pull request by twangxxx**

### CODE REVIEW

**Comment by marouenbg** [comment]
@twangxxx I had an error with system.file recently, I'd say the problem is there.

**Comment by twangxxx** [comment]
> @twangxxx I had an error with system.file recently, I'd say the problem is there.

@marouenbg If you meant that error appears frequently these days, that's wired, because the recent tests actually passed. I am not sure why this system.file error did not affect the build result.

**Comment by marouenbg** [comment]
@twangxxx do you use system.file elsewhere? if not try loading the data with a different function. I think it is related to R4

**Comment by twangxxx** [comment]
@marouenbg In almost every example code in function documentation and almost every test, I use system.file().  Will find a workaround to load data today.

This PR ran some panda tests including 4 Panda network(used TB data, ~ 15101200 edges each network), it took 9 hrs to run.

### Updates: 

current code coverage is:
**Bold font means at least one inevitable PANDA network will be built during the unit test** 

netZooR Coverage: 44.44%

- **R/LIONESS.R**: 0.00%
- R/MONSTER.R: 0.00%  # encounter  an error in code, will post an issue soon later.
- **R/panda.diff.edges.R**: 0.00%
- **R/panda.to.alpaca.R**: 0.00%
- **R/panda.to.condor.object.R:** 0.00%
- R/vis.diff.panda.in.cytoscape.R: 0.00%         # unable to test as cytoscape need to be installed and launched to interactive
- R/vis.panda.in.cytoscape.R: 0.00%               # unable to test like above
- R/create.diff.panda.style.R: 6.67%                # unable to test like above
- R/create.panda.style.R: 6.67%                      # unable to test like above
- R/ALPACA.R: 35.63%                                     # could add more tests
- R/CONDOR.R: 89.32%
- **R/PANDA.R: 92.42%**
- R/SAMBAR.R: 95.38%
- R/OTTER.R: 100.00%
- R/source.PPI.R: 100.00%

I'd like to fix loading data issue first to see if there is any acceleration in Jenkins build.

**Comment by twangxxx** [comment]
@marouenbg , nvm, MONSTER error I probably could fix it by myself.

**Comment by marouenbg** [comment]
@twangxxx in the tests you are not using system.file you are using load("./testDataset.RData")

**Comment by twangxxx** [comment]
@marouenbg you are right, I was wrong, [test-panada.r](https://github.com/netZoo/netZooR/blob/dc0773f00211de35cfbc935f3534d644cd480f27/tests/testthat/test-panda.R) is the only test script used system.file.  system.file() is also used in most function documents. 

Did system.file error appear only in this PR?

**Comment by marouenbg** [comment]
there was no error with system.file() in this PR because it passed. I had an error with it with a script for another project. It would make sense because the error we had in the beginning was memory error (segfault).

**Comment by marouenbg** [comment]
Hi @twangxxx did you have a look at this to fix panda test?

> @twangxxx I had an error with system.file recently, I'd say the problem is there.

**Comment by twangxxx** [comment]
> Hi @twangxxx did you have a look at this to fix panda test?
> 
> > @twangxxx I had an error with system.file recently, I'd say the problem is there.

@marouenbg , did you mean the system.file error? I didn't see that error relevant to this PR so it is not clear to me where to fix.

**Comment by marouenbg** [comment]
@twangxxx  ok I thought this was the PR for the failing panda test with jenkins

**Comment by twangxxx** [comment]
> @twangxxx ok I thought this was the PR for the failing panda test with jenkins

@marouenbg , that was test for monster #152. It passed eventually then I merged it to devel. Good night ;)

**Comment by marouenbg** [comment]
ok good job then !

**Pull request closed without merging**
