### PR TITLE
Add TIGER

### PR DESCRIPTION
**Pull request by cchen22**

### CODE REVIEW

**Comment by cchen22** [comment]
@marouenbg I have updated the "TIGER.R" file in the "R" folder and added two example data files, "expr.rda" and "prior.rda," to the "data" folder. Please let me know if these changes are sufficient?

**Comment by cchen22** [comment]
@marouenbg The situation is more complex than I initially thought. I have now documented everything and successfully tested the "example(TIGER)" on my end. However, an error message indicates that the "cmdstanr" R package needs to be installed. I'm unsure about the best course of action, as it requires two steps outlined in my [ReadMe file](https://github.com/cchen22/TIGER)
1. Install the "cmdstanr" package by running the command: `install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))`
2. Install cmdstan by running the command: `cmdstanr::install_cmdstan()`

Please advise on how to proceed.
Thank you!

**Comment by marouenbg** [comment]
Oh I se, can you add the package in the depends section here: https://github.com/netZoo/netZooR/blob/master/DESCRIPTION#L24

**Comment by marouenbg** [comment]
Does it work on your end after adding it to the dependencies?

**Comment by cchen22** [comment]
> Does it work on your end after adding it to the dependencies?

No. `ERROR: dependency 'cmdstanr' is not available for package 'netZooR'`

**Comment by marouenbg** [comment]
OK remove it from descsription and try running this function at the root of netZoooR https://mc-stan.org/rstantools/reference/use_rstan.html

**Comment by cchen22** [comment]
> OK remove it from description and try running this function at the root of netZooR https://mc-stan.org/rstantools/reference/use_rstan.html and upload the new updated files to this PR

This appears to be a pipeline for rstan, not for cmdstanr. Unfortunately, these are two separate packages... When I created TIGER, I searched for a solution to this question but had no luck. However, I came across a potentially useful repository: https://github.com/rok-cesnovar/misc/tree/master/democmdstanr. I will examine it and inform you later.

**Comment by marouenbg** [comment]
You can also add a remotes section in description like so
Remotes:
    stan-dev/cmdstanr

**Comment by cchen22** [comment]
> You can also add a remotes section in description like so Remotes: stan-dev/cmdstanr

I finally applied this method and added a `.onLoad` function to check and install stan when netZooR is loaded. On my end cmdstanr can be successfully installed and  `example(TIGER)` works fine. However, I encountered some error messages that don't appear to be related to Stan. Could you share your thoughts on this? Thanks!

**Comment by marouenbg** [comment]
OK, I am on it now.

**Comment by marouenbg** [comment]
yep, here is how that data file was documented in CONDOR.R https://github.com/netZoo/netZooR/blob/81cb072fd4f3e1b47b99ef2ce67d1cad6a83bde1/R/CONDOR.R#L1032

**Comment by marouenbg** [comment]
Thanks @cchen22 , this should be fine for this iteration, we will add tests in a new PR.

**Comment by marouenbg** [comment]
@cchen22 everything looks good, merging now. 
Fantastic work!
Please use Tiger from the netZooR distribution so that you use the same version used by others which makes it easier to replicate bugs etc...

**Comment by marouenbg** [comment]
Hi @cchen22 , would it be possible to update the TIGER vignette using netZooR code? Thank you!

**Comment by cchen22** [comment]
> Hi @cchen22 , would it be possible to update the TIGER vignette using netZooR code? Thank you!

Sure! But do you want me to start a new PR?

**Comment by marouenbg** [comment]
Yes, here please https://github.com/netZoo/netbooks

**Comment by marouenbg** [comment]
Hello @cchen22, would it be possible to add a small description of TIGER in the readme file through a new pull request? Thank you https://github.com/netZoo/netZooR/blob/devel/README.md

**Pull request merged**
