### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by marouenbg**

### CODE REVIEW

**Comment by twangxxx** [comment]
Very nice work!

let me know when you think it's ready to merge into **devel**, as I'd like to use NEW version travis.yml file in my next PR.

**Comment by twangxxx** [comment]
@marouenbg Very nice work! let me know when you finis

**Comment by twangxxx** [comment]
close by mistake ;(

**Comment by marouenbg** [comment]
@twangxxx thanks ! still loads of things to do

**Comment by zookeeper-dev** [comment]
Can one of the admins verify this patch?

**Pull request merged**
