### PR TITLE
add otter tutorial

### PR DESCRIPTION
**Pull request by rebekka-burkholz**
add otter tutorial

### CODE REVIEW

**Comment by marouenbg** [comment]
@twangxxx Check this out.

**Comment by twangxxx** [comment]
What? Still building...?

**Comment by marouenbg** [comment]
Do you know why it is taking too long? It seems that it passed the OTTER tutorial part.

**Comment by marouenbg** [comment]
@twangxxx  In the new R4.0, `\donttrun` seems more reliable than `\donttest`. Reference: https://github.com/r-lib/devtools/issues/2216
How many instances do we have in the package? Could that be related to the slow run time?

**Comment by twangxxx** [comment]
@marouenbg I doubt that, not sure but I am feeling the /donttest basically will be excluded from executing so it won't take any time to run.

I remembered at that time when I was off(ten hours ago), the process was pending at the same place as now.

**Comment by marouenbg** [comment]
Check the reference I sent you, they said that R 4.0 will run those examples anyway. The reason is that the new behavior of `R CMD CHECK` will call run-donttest instead of the plain run, which will basically run the donttest sections.

**Comment by twangxxx** [comment]
> Check the reference I sent you, they said that R 4.0 will run those examples anyway. The reason is that the new behavior of `R CMD CHECK` will call run-donttest instead of the plain run, which will basically run the donttest sections.

@marouenbg In that case, switching all \donttes to \dontrun?
Per searching https://github.com/netZoo/netZooR/search?q=donttest, there are 4 \donttest in MONSTER.r.

**Comment by marouenbg** [comment]
lol 30 minutes
dance

**Comment by marouenbg** [comment]
@twangxxx the reason it become so fast is due to 2 things:
- ignoring vignettes in the build and check steps
- a new linear algebra library that makes netZooR much much faster (https://csantill.github.io/RPerformanceWBLAS/)

If you recall things that we had to cut to make the server faster, it is time to put them back.

**Comment by twangxxx** [comment]
> @twangxxx the reason it become so fast is due to 2 things:
> 
> * ignoring vignettes in the build and check steps
> * a new linear algebra library that makes netZooR much much faster (https://csantill.github.io/RPerformanceWBLAS/)
> 
> If you recall things that we had to cut to make the server faster, it is time to put them back.

@marouenbg quick sum-up:

1. uncomment all tests commented in netZooR/tests/testthat/test-monster.r before you have all bugs in monster source code fixed, and have all @example code chunk worked

2. fix python script of panda when 1)only expression data as input; 2)ppi is not provided; 
Then uncomment test 2-4 in test-panda.r from this line https://github.com/netZoo/netZooR/blob/master/tests/testthat/test-panda.R#L14 and test 2-3 in test-lioness.r from this line https://github.com/netZoo/netZooR/blob/master/tests/testthat/test-lioness.R#L14

**Pull request merged**
