### PR TITLE
put monster vignette back

### PR DESCRIPTION
**Pull request by twangxxx**

### CODE REVIEW

**Comment by twangxxx** [comment]
Quitting from lines **103-104 (MONSTER.Rmd)** 
Error: processing vignette 'MONSTER.Rmd' failed with diagnostics:
numeric 'names' must be >= 1
--- failed re-building ‘MONSTER.Rmd’


where the bug is located:
**monsterRes <- monster(yeast$exp.cc, design, yeast$motif, nullPerms=100, numMaxCores=1)**

**Comment by marouenbg** [comment]
@twangxxx what is the situation with this one?

**Comment by twangxxx** [comment]
> @twangxxx what is the situation with this one?

@marouenbg For some unknown reasons, the revised **MONSTER vignette**(https://github.com/netZoo/netZooR/blob/9b29bdce2a21b30eb506e4ca557c48572ec40c5e/vignettes/MONSTER.Rmd) doesn't work well with Jenkin, so I removed it from the netZooR repo, in both the master and devel branch.

Quote from the message I left in August about the error, also located [here ](http://zookeeper.networkmedicine.org/job/netZooR_Ubuntu18.04/138/console)
> Quitting from lines 103-104 (MONSTER.Rmd)
> Error: processing vignette 'MONSTER.Rmd' failed with diagnostics:
> numeric 'names' must be >= 1
> --- failed re-building ‘MONSTER.Rmd’
> 
> where the bug is located:
> monsterRes <- monster(yeast$exp.cc, design, yeast$motif, nullPerms=100, numMaxCores=1)

**Comment by marouenbg** [comment]
@twangxxx So I was able to fix this, can you point me to MONSTER vignette file to put it back? Also I see that you have a handbook for adding tutorials, which is pretty cool, do you want to include it?

**Comment by twangxxx** [comment]
@marouenbg 

revised MONSTER vignette: (https://github.com/netZoo/netZooR/blob/9b29bdce2a21b30eb506e4ca557c48572ec40c5e/vignettes/MONSTER.Rmd


I remember the handbook didn't work for some reason last time. That will be great if you'd like to fix it based on what I've done, otherwise, I probably could work on it this weekend.
Handbook:
https://github.com/netZoo/netZooR/blob/9b29bdce2a21b30eb506e4ca557c48572ec40c5e/vignettes/netZooRDevelopmentHandbook.Rmd

**Comment by marouenbg** [comment]
I will add back monster tutorial for now, if you could please have a look at the hand book that would be awesome  XD

**Comment by twangxxx** [comment]
> I will add back monster tutorial for now, if you could please have a look at the hand book that would be awesome XD

haha i will do that until your put-monster-vignette-back build passes. 😴 get back to you tomorrow morning

**Comment by marouenbg** [comment]
fixed in https://github.com/netZoo/netZooR/pull/168

**Pull request closed without merging**
