### PR TITLE
Fixed the Errors in pkgdown Website Build

### PR DESCRIPTION
**Pull request by taraeicher**
Addressed the following issues that were causing pkgdown::build_site() to fail:

- References from BLOBFISH and YARN were missing from the YAML file as well as some of the data sets used in the vignettes. Fixed this by adding the references to the YAML file.
- There was a mismatch between the vignette names in the YAML file and the values in the VignetteIndexEntry fields within the vignettes. Fixed this by modifying the VignetteIndexEntry fields.

### CODE REVIEW

**Comment by marouenbg** [comment]
Hey @taraeicher , so pngs you deleted, do you need to stop track them in GitHub as well? https://github.com/netZoo/netZooR/blob/master/.gitignore

**Comment by taraeicher** [comment]
Okay, I can remove the last commit from the pull request then.


Sent from Yahoo Mail for iPhone


On Friday, July 12, 2024, 9:46 AM, Marouen ***@***.***> wrote:




@taraeicher I think those png files cannot be deleted because they are necessary for building the website.

**Comment by marouenbg** [comment]
yes, that would be great @taraeicher

**Pull request merged**
