### PR TITLE
Adding Tiger

### PR DESCRIPTION
**Pull request by cchen22**
Add TIGER.R from https://github.com/cchen22/TIGER

### CODE REVIEW

**Comment by marouenbg** [comment]
Hey @cchen22 , thank you for this great contribution.
Can you please transform the readme.md from your repo https://github.com/cchen22/TIGER/blob/master/README.md to a Jupyter notebook and push it as a vignette in netbooks, you can create a PR here: https://github.com/netZoo/netbooks/tree/main/netbooks/netZooR

**Comment by marouenbg** [comment]
Hi @cchen22 ,
Happy new year! I haven't forgotten about this, I waiting for an older PR to correct an old release, then we add TIGER in.

**Comment by cchen22** [comment]
Hi @marouenbg ,
Happy new year! Please take your time and let me know if there is any issue with TIGER.

**Comment by marouenbg** [comment]
Hey @cchen22 ,

Sorry this took so long, we had a Bioconductor issue that we just fixed.
So can you have a final quick look at this before merging into devel?
Also please:
- once I merge in devel, please install netZooR devel and see if Tiger works as intended
- maintain and update new TIGER versions through netZooR by using pull requests
- mention netZooR v1.4 in your manuscript software availability
- it would be great if you could mention the netZoo publication (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02877-1)
- You can also upload your use case as a Jupyter notebook here: http://netbooks.networkmedicine.org/hub/login; let me know if you're interested and I will walk you through it

**Comment by marouenbg** [comment]
Feel free to reopen when you're ready to proceed!

**Comment by cchen22** [comment]
Hi @marouenbg 

Apologies for the delayed response. I have been preoccupied with my graduation requirements this month. I am now ready to incorporate TIGER into netzooR, which I am really looking forward to.

I reviewed your checklist and it seems TIGER meets most of the criteria. I will delete my GitHub repository after merging TIGER into netzooR. I will also be sure to acknowledge netzooR in the TIGER manuscript.
Please let me know if there are any specific items I should double-check before merging. 

Thank you,
Chen

**Comment by marouenbg** [comment]
Congrats @cchen22, this is great to hear ! 🥳 
Let's resume netZooR integration then

**Pull request merged**
