### PR TITLE
Fix alpaca & add more tests

### PR DESCRIPTION
**Pull request by twangxxx**
- update to version 0.7.3
- fix alpaca regular expression mismatch bug
- add three more tests

### CODE REVIEW

**Comment by twangxxx** [comment]
Hey @marouenbg , any suggestion on this failed build? It said `Error in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  : 
  file size is limited to 8GB`, but in my PC, it's 485 Mb.

**Comment by marouenbg** [comment]
Hey @twangxxx , The server has only 8Gb of RAM, that's why you had that error. Try downscaling the test size.

**Comment by twangxxx** [comment]
> Hey @twangxxx , The server has only 8Gb of RAM, that's why you had that error. Try downscaling the test size.

@marouenbg , I doubt that this is related to test size, as It seems it failed at very early stages in `building ‘netZooR_0.7.3.tar.gz’.`.

**Comment by marouenbg** [comment]
I am pretty sure it has to do with IO larger than RAM, because 8Gb in the error message corresponds to the RAM size.

**Comment by twangxxx** [comment]
> I am pretty sure it has to do with IO larger than RAM, because 8Gb in the error message corresponds to the RAM size.

@marouenbg, got it! thank you!

**Pull request closed without merging**
