### PR TITLE
Test monster 

### PR DESCRIPTION
**Pull request by twangxxx**

### CODE REVIEW

**Comment by twangxxx** [comment]
@marouenbg, any thoughts on why there are two CMD checks in the last commit, former one result status is `Status: 1 NOTE` and latter one  is `Status: 2 ERRORs, 1 NOTE` in build [# 78](http://zookeeper.networkmedicine.org/job/netZooR_Ubuntu18.04/78/console)?

**Comment by marouenbg** [comment]
@twangxxx try re-running the build again.

**Comment by marouenbg** [comment]
@twangxxx Does it pass locally?

**Comment by twangxxx** [comment]
> @twangxxx Does it pass locally?

@marouenbg , just double-checked, it could pass check locally.

**Comment by marouenbg** [comment]
@twangxxx I changed the folder permissions and restarted the build. It is weird though because Jenkins has all folder access permissions. See that's what bugs me with R, since the description file has many dependencies, a change in one of them can fail the build overnight.

**Comment by marouenbg** [comment]
@twangxxx as for why jenkins has two builds, one that succeds and one fails, the build log says that it is testing netZooR 0.7.1 and 0.7.2 so double check that the version is consistent everywhere.

**Pull request merged**
